---
- hosts: "localhost"
  become: true
  tasks:
    - name: ensure postfix packages are installed
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      vars:
        packages:
          - postfix
      tags: init postfix

    - name: ensure postfix packages are uninstalled
      apt:
        pkg: "{{ packages }}"
        state: absent
        update_cache: yes
        cache_valid_time: 600
      vars:
        packages:
          - postfix
      tags: drop postfix

    - name: ensure all postfix services are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - postfix
      tags: init postfix
    
    - name: ensure all postfix services are absent and disabled
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - postfix
      tags: drop postfix


